    graph TD
     A[Open the Windows CMD line] -->
     B[Enter `notepad hello.cpp`] -->
     C[Enter the program] -->
     D[Save the program] -->
     E[CMD: `g++ hello.cpp -o hello++`] -->
     |May not work for g++ 13.2| F[CMD: `hello++`] --> 
     G[Canvas: upload `hello.cpp`]