---
title: Rectangle1
---
graph TD
    A[Start] -->
    B[Get `length` of rectangle] -->
    C[Get `width` of rectangle] -->
    D[Compute `area = length * width`] -->
    E[Compute `perimeter = 2 * (length + width)`] -->
    F[Print `area` and `perimeter`] -->
    G[Stop]
