#+title: Loop Lab
#+author: [yourname] (pledged)
#subtitle: Intro to programming in C++ (CSC 100) Lyon College Spring 2024
#+startup: overview hideblocks indent entitiespretty:
#+property: header-args:C :main yes :includes <stdio.h> :results output :exports both :tangle yes: 
#+options: toc:nil num:nil
* Loop Exercises in C

Three exercises for class practice:
1) pick any of these to begin with and complete it in class
2) submit one or all of them later for bonus points in Canvas.
3) Use the pseudocode block to document your approach, and the
   "Lessons learnt" block below to record your observations or
   insights (if any).
   
** Exercise 1: Sum of Even Numbers Using a =while= Loop

1) Write a C program that calculates the sum of even numbers between 1
   and 100 inclusive using a while loop.

2) Pseudocode:
   #+begin_example

   #+end_example

3) Code:
   #+begin_src C

   #+end_src

4) Lessons learnt:
   #+begin_quote

   #+end_quote

** Exercise 2: Reverse a Number Using a =do-while= Loop

1) Write a C program that reverses the digits of a number using a
   do-while loop. For instance, if the input is 1234, the output
   should be 4321.

   Tip: 1234 = 10^0 * 4 + 10^1 * 3 + 10^2 * 2 + 10^3 * 1. It follows
   that 1234 % 10 = 4, 1234 / 10 = 123.4, 123 % 10 = 3, 123 / 10 =12.3
   etc.
   #+begin_src C
     printf("%d\n",1234%10);
     printf("%d\n",1234/10);
     printf("%d\n",123%10);
     printf("%d\n",123/10);
     printf("%d\n",12%10);
     printf("%d\n",12/10);
     printf("%d\n",1%10);
     printf("%d\n",1/10);
   #+end_src

2) Pseudocode:
   #+begin_example

   #+end_example

3) Code
   #+begin_src C :main yes :includes <stdio.h> :results output

   #+end_src

4) Lessons learnt:
   #+begin_quote

   #+end_quote

** Exercise 3: Calculate the Factorial of a Number Using a =for= Loop

Write a C program that calculates the factorial of a number using a
for loop. The factorial of a number n is the product of all positive
integers less than or equal to n, e.g. for n = 4: 4! = 4 * 3 *
2 * 1. 0! is defined to be 1.

2) Pseudocode:
   #+begin_example

   #+end_example

3) Code:
   #+begin_src C :main yes :includes <stdio.h> :results output :exports both :tangle yes

   #+end_src

4) Lessons learnt:
   #+begin_quote

   #+end_quote

