#+TITLE: ...
#+AUTHOR: ...
#+SUBTITLE:Bonus programming assignment 2 - Intro to Programming in C, Spring 2023
#+OPTIONS: toc:nil num:nil ^:nil
#+PROPERTY: header-args:C :main yes :includes <stdio.h> :exports both
#+STARTUP:overview hideblocks indent
* Problem

1) Modify the program that converted three specific height values from
   meters to light-years to compute the light-year equivalent of any
   one height value in meters passed to the program as input.

   [[https://github.com/birkenkrahe/cc/blob/piHome/org/bonus_pgm_1.org#solution][You can find the solution here.]]

2) Enter the three heights from the first program as test cases as
   *command line input*. To do this in Emacs, use the ~:cmdline < input~
   header argument. The input file should only contain one number.

For example, if the ~input~ file contains Napoleon's height (1.67) in
metres, the output would be: ~A height of 1.67 m is equivalent to
1.77e-16 light-years~. 

* Submission

Submit your solution as an Emacs Org-mode file including the usual
header information (title, author, pledged), in Canvas.

The solution should contain the output after the code block. It looks
like this:
#+begin_example
  : A height of 1.80 m is equivalent to 1.9039e-16 light-years
#+end_example

* TODO Solution

