#+TITLE: Practicing functions
#+AUTHOR: [yourname] [pledged]
#+STARTUP: overview hideblocks indent
* README

- Practice workbook for functions in C

* Identify yourself

- replace the placeholder ~[yourName]~ in the header of this file by
  your name and save the file (~C-x C-s~).

* TODO ~hello_world~ function

1) The ~hello_world~ function does not have a ~return~ value, and it takes
   no arguments. Complete the code in [[f:hello_world]] so that it compiles
   and runs.

2) Remember that all statements that you want to execute need to be
   contained in the body of the ~main~ function but user-defined
   functions can be defined outside of ~main~.

3) You have to add ~main~ and =include= the necessary macros.

   #+name: f:hello_world
   #+begin_src C :results output
     // function definition
     hello_world()
     {
       printf("Hello world\n");
     }
     // function call
     hello_world();
   #+end_src

* TODO Back to basics - the command line

1) Add the header argument ~:tangle hello.c~ to the code block of your
   last solution.

2) Tangle the source code file ~hello.c~ with ~C-u C-c C-v t~.

3) Compile and run the file on the command line:
   - Split the screen (~C-x 2~)
   - Open a shell in Emacs (~M-x eshell~)
   - Compile and run the ~hello.c~ file
   - Kill the ~*eshell*~ buffer with ~C-x 0~ and return here.

* TODO Save a function return value

1) Complete the ~average~ function in [[f:avg]] below, save and print its
   value.

   Sample output:
   #+begin_example
   : The average of 5.1 and 8.9 is: 7
   #+end_example

2) The function is already defined at the top of the code block, and
   two ~double~ values are declared and defined, too.

3) /Tip: remember to declare your variable. Use ~%g~ for the output./

   #+name: f:avg
   #+begin_src C
     // function definition

     // Input variable declaration and definition
     x = 5.1, y = 8.9;

     // Save the average of x and y in a variable avg

     // Print the variable avg

   #+end_src

* TODO Write your own function

1) Write a function ~add~ that adds two integer numbers ~num1~ and ~num2~.

2) Call the function ~add~ inside the ~printf~ function for the sample
   arguments ~x=100~ and ~y=200~.

   Sample output:
   #+begin_example
   : 100 + 200 = 300
   #+end_example

   #+name: func:add
   #+begin_src C
     // preprocessor directive

     // function definition

     // main function

     // declare and initialize variables

     // function call and print

   #+end_src

* TODO Encapsulate a formula

Problem: Compute log10 squared (square of the logarithm base 10) and
print the result for the test value x=100 (the result should be 4).

Constraint: define a function ~l2~ that accepts a single argument and
returns the logarithm to base 10 of its argument squared.

Tip: =log10= is defined in =math.h=.

#+begin_src C :libs -lm
  // macros

  // function definition

  // main function

    // declaration and initialization of variables

    // compute and print result

#+end_src
